export const browserCoreExamples = [
  "idlehands browser status",
  "idlehands browser start",
  "idlehands browser stop",
  "idlehands browser tabs",
  "idlehands browser open https://example.com",
  "idlehands browser focus abcd1234",
  "idlehands browser close abcd1234",
  "idlehands browser screenshot",
  "idlehands browser screenshot --full-page",
  "idlehands browser screenshot --ref 12",
  "idlehands browser snapshot",
  "idlehands browser snapshot --format aria --limit 200",
  "idlehands browser snapshot --efficient",
  "idlehands browser snapshot --labels",
];

export const browserActionExamples = [
  "idlehands browser navigate https://example.com",
  "idlehands browser resize 1280 720",
  "idlehands browser click 12 --double",
  'idlehands browser type 23 "hello" --submit',
  "idlehands browser press Enter",
  "idlehands browser hover 44",
  "idlehands browser drag 10 11",
  "idlehands browser select 9 OptionA OptionB",
  "idlehands browser upload /tmp/idlehands/uploads/file.pdf",
  'idlehands browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "idlehands browser dialog --accept",
  'idlehands browser wait --text "Done"',
  "idlehands browser evaluate --fn '(el) => el.textContent' --ref 7",
  "idlehands browser console --level error",
  "idlehands browser pdf",
];
